theme: jekyll-theme-hacker
title: davemason.dev
description: A blog site for Dave Mason. I'm a software engineering lead from Manchester, UK. Here I'll write about some techie stuff and some leadership stuff.
show_downloads: false
google_analytics: G-QB8JDF66VZ